# Generated by Django 4.1.7 on 2023-03-30 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagina',
            name='cuerpo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagina',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pagina',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='subtitulo',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pagina',
            name='titulo',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
