# Generated by Django 4.1.7 on 2023-03-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_pagina_autor_pagina_cuerpo_pagina_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='cuerpo',
            field=models.TextField(null=True),
        ),
    ]
