# Generated by Django 4.1.7 on 2023-03-31 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.TextField(null=True)),
                ('fecha', models.DateTimeField(null=True)),
                ('de', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='de_messages', to=settings.AUTH_USER_MODEL)),
                ('para', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='para_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
