# Generated by Django 4.1.7 on 2023-03-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='camada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='camada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='cursos',
            field=models.IntegerField(),
        ),
    ]
