# Generated by Django 4.1.7 on 2023-03-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_alter_curso_camada_alter_estudiante_camada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='camada',
            field=models.IntegerField(unique=True),
        ),
    ]
