# Generated by Django 4.1.7 on 2023-03-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_alter_curso_camada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='cursos',
            field=models.CharField(max_length=40),
        ),
    ]
